 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/steps", type: :request do
  # Step. As you add validations to Step, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Step.create! valid_attributes
      get steps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      step = Step.create! valid_attributes
      get step_url(step)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      # get new_step_url
      # expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      step = Step.create! valid_attributes
      get edit_step_url(step)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Step" do
        expect {
          post steps_url, params: { step: valid_attributes }
        }.to change(Step, :count).by(1)
      end

      it "redirects to the created step" do
        post steps_url, params: { step: valid_attributes }
        expect(response).to redirect_to(step_url(Step.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Step" do
        expect {
          post steps_url, params: { step: invalid_attributes }
        }.to change(Step, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post steps_url, params: { step: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested step" do
        step = Step.create! valid_attributes
        patch step_url(step), params: { step: new_attributes }
        step.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the step" do
        step = Step.create! valid_attributes
        patch step_url(step), params: { step: new_attributes }
        step.reload
        expect(response).to redirect_to(step_url(step))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        step = Step.create! valid_attributes
        patch step_url(step), params: { step: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested step" do
      step = Step.create! valid_attributes
      expect {
        delete step_url(step)
      }.to change(Step, :count).by(-1)
    end

    it "redirects to the steps list" do
      step = Step.create! valid_attributes
      delete step_url(step)
      expect(response).to redirect_to(steps_url)
    end
  end
end
